package crypto

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"fmt"
	"io"
)

// idAlphabet is a 32-character alphabet with the look-alike characters removed:
// no "l" or "1", no "o" or "0". Identifiers built from it survive being read over
// the phone, pasted out of a screenshot, or typed from a support ticket.
//
// Its length being exactly 32 also means a random byte maps onto it with no
// modulo bias, so sampling needs no rejection loop.
const idAlphabet = "abcdefghijkmnpqrstuvwxyz23456789"

// Identifier lengths. Both are generated by the application before insert, so
// neither depends on a database sequence.
const (
	// statsKeyLength gives about 60 bits. The stats key is an immutable public
	// identifier, not a secret: it appears in Xray logs on every node.
	statsKeyLength = 12

	// subscriptionTokenLength gives about 110 bits. This one is a bearer secret:
	// whoever holds it can fetch a user's subscription.
	subscriptionTokenLength = 22
)

// RandomBytes returns n cryptographically random bytes.
func RandomBytes(n int) ([]byte, error) {
	if n <= 0 {
		return nil, fmt.Errorf("crypto: random byte count %d must be positive", n)
	}
	b := make([]byte, n)
	if _, err := io.ReadFull(rand.Reader, b); err != nil {
		return nil, fmt.Errorf("crypto: read random bytes: %w", err)
	}
	return b, nil
}

// RandomToken returns nBytes of randomness encoded as unpadded base64url, safe to
// put in a URL, a header or a cookie.
func RandomToken(nBytes int) (string, error) {
	b, err := RandomBytes(nBytes)
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// RandomID returns an identifier of the given length over [idAlphabet].
func RandomID(length int) (string, error) {
	if length <= 0 {
		return "", fmt.Errorf("crypto: identifier length %d must be positive", length)
	}
	b, err := RandomBytes(length)
	if err != nil {
		return "", err
	}
	out := make([]byte, length)
	for i, v := range b {
		// len(idAlphabet) is 32 and divides 256, so this is unbiased.
		out[i] = idAlphabet[int(v)%len(idAlphabet)]
	}
	return string(out), nil
}

// NewStatsKey returns a fresh value for users.xray_email.
//
// It is immutable for the lifetime of the user: renaming a user must not change
// the key Xray reports traffic under, otherwise a rename would turn into a
// remove-and-add across every node. See docs/decisions.md, ADR-007.
func NewStatsKey() (string, error) { return RandomID(statsKeyLength) }

// NewSubscriptionToken returns a fresh value for users.short_uuid, the secret in
// the public /sub/{token} URL.
//
// It is deliberately not reused as the stats key: that would leak a bearer secret
// into the Xray logs of every node.
func NewSubscriptionToken() (string, error) { return RandomID(subscriptionTokenLength) }

// HashToken returns the SHA-256 of a bearer token.
//
// Tokens are stored hashed so that a leaked database dump does not hand over live
// credentials. SHA-256 with no salt or stretching is the right choice here and the
// wrong one for passwords: these tokens carry full random entropy, so there is no
// guessable input to slow an attacker down over, and lookup by hash has to be a
// single indexed query.
func HashToken(token string) []byte {
	sum := sha256.Sum256([]byte(token))
	return sum[:]
}

// EqualHash compares two hashes in constant time.
func EqualHash(a, b []byte) bool {
	return subtle.ConstantTimeCompare(a, b) == 1
}
