package config

import (
	"encoding/json"
	"reflect"
	"testing"
)

// TestApplyMergePatchRFC7386 runs the conformance table from RFC 7386 Appendix A.
//
// It is here because the reason for implementing merge patch rather than importing it
// was confidence in one specific behaviour: null deletes a key. The appendix is the
// authoritative statement of that and of every neighbouring case, so running it is
// cheaper than arguing about them.
func TestApplyMergePatchRFC7386(t *testing.T) {
	cases := []struct {
		target string
		patch  string
		want   string
	}{
		{`{"a":"b"}`, `{"a":"c"}`, `{"a":"c"}`},
		{`{"a":"b"}`, `{"b":"c"}`, `{"a":"b","b":"c"}`},
		{`{"a":"b"}`, `{"a":null}`, `{}`},
		{`{"a":"b","b":"c"}`, `{"a":null}`, `{"b":"c"}`},
		{`{"a":["b"]}`, `{"a":"c"}`, `{"a":"c"}`},
		{`{"a":"c"}`, `{"a":["b"]}`, `{"a":["b"]}`},
		{`{"a":{"b":"c"}}`, `{"a":{"b":"d","c":null}}`, `{"a":{"b":"d"}}`},
		{`{"a":[{"b":"c"}]}`, `{"a":[1]}`, `{"a":[1]}`},
		{`["a","b"]`, `["c","d"]`, `["c","d"]`},
		{`{"a":"b"}`, `["c"]`, `["c"]`},
		{`{"a":"foo"}`, `null`, `null`},
		{`{"a":"foo"}`, `"bar"`, `"bar"`},
		{`{"e":null}`, `{"a":1}`, `{"e":null,"a":1}`},
		{`[1,2]`, `{"a":"b","c":null}`, `{"a":"b"}`},
		{`{}`, `{"a":{"bb":{"ccc":null}}}`, `{"a":{"bb":{}}}`},
	}

	for _, tc := range cases {
		t.Run(tc.target+" + "+tc.patch, func(t *testing.T) {
			got, err := ApplyMergePatch([]byte(tc.target), []byte(tc.patch))
			if err != nil {
				t.Fatalf("ApplyMergePatch: %v", err)
			}
			assertJSONEqual(t, got, []byte(tc.want))
		})
	}
}

// assertJSONEqual compares two documents by value, since the merge output is indented
// and key order is not part of the contract.
func assertJSONEqual(t *testing.T, got, want []byte) {
	t.Helper()

	var gotValue, wantValue any
	if err := json.Unmarshal(got, &gotValue); err != nil {
		t.Fatalf("result is not valid JSON (%v): %s", err, got)
	}
	if err := json.Unmarshal(want, &wantValue); err != nil {
		t.Fatalf("expectation is not valid JSON (%v): %s", err, want)
	}
	if !reflect.DeepEqual(gotValue, wantValue) {
		t.Errorf("got %s, want %s", got, want)
	}
}

// TestEmptyPatchIsAByteForByteNoOp matters because the stored default for
// nodes.config_patch is an empty object. If applying it reserialised the document, the
// generated bytes would differ from the unpatched ones and every hash comparison would
// see a change.
func TestEmptyPatchIsAByteForByteNoOp(t *testing.T) {
	target := []byte("{\n  \"a\": 1,\n  \"b\": [2, 3]\n}")

	for _, patch := range []string{"", "{}"} {
		got, err := ApplyMergePatch(target, []byte(patch))
		if err != nil {
			t.Fatalf("ApplyMergePatch(%q): %v", patch, err)
		}
		if string(got) != string(target) {
			t.Errorf("patch %q reserialised the document:\n got: %s\nwant: %s", patch, got, target)
		}
	}
}

func TestApplyMergePatchRejectsInvalidJSON(t *testing.T) {
	if _, err := ApplyMergePatch([]byte(`{"a":1}`), []byte(`{not json`)); err == nil {
		t.Error("an invalid patch was accepted")
	}
	if _, err := ApplyMergePatch([]byte(`{not json`), []byte(`{"a":1}`)); err == nil {
		t.Error("an invalid target was accepted")
	}
}

// TestMergePatchReplacesArraysWholesale pins the behaviour an operator has to know
// about: there is no element-wise merge, so overriding outbounds means supplying the
// whole list.
func TestMergePatchReplacesArraysWholesale(t *testing.T) {
	target := []byte(`{"outbounds":[{"protocol":"freedom","tag":"direct"},{"protocol":"blackhole","tag":"blocked"}]}`)
	patch := []byte(`{"outbounds":[{"protocol":"freedom","tag":"direct"}]}`)

	got, err := ApplyMergePatch(target, patch)
	if err != nil {
		t.Fatalf("ApplyMergePatch: %v", err)
	}

	var document struct {
		Outbounds []map[string]any `json:"outbounds"`
	}
	if err := json.Unmarshal(got, &document); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if len(document.Outbounds) != 1 {
		t.Errorf("got %d outbounds, want 1: arrays must be replaced, not merged", len(document.Outbounds))
	}
}

// TestMergePatchCanDeleteAGeneratedSection is the operator-facing case the null
// behaviour exists for.
func TestMergePatchCanDeleteAGeneratedSection(t *testing.T) {
	spec := Spec{
		NodeName: "de-1",
		Defaults: Defaults{
			LogLevel:   "warning",
			APIAddress: "127.0.0.1",
			APIPort:    10085,
			DNSServers: []string{"1.1.1.1"},
		},
		ConfigPatch: json.RawMessage(`{"dns":null}`),
		Inbounds: []Inbound{{
			Tag:        "vless-reality",
			Protocol:   ProtocolVLESS,
			Transport:  TransportTCP,
			Security:   SecurityReality,
			ListenPort: 443,
			Reality:    testReality(),
			Clients:    vlessClients()[:1],
		}},
	}

	generated, err := Generate(spec)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	var document map[string]any
	if err := json.Unmarshal(generated.JSON, &document); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if _, present := document["dns"]; present {
		t.Error("a null patch did not remove the generated dns section")
	}
}
