// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: xray/common/protocol/user.proto

package protocol

import (
	serial "github.com/xraypanel/panel/internal/xray/common/serial"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User is one account on one inbound.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Level selects the policy that applies. The panel generates policy.levels.0 with
	// the per-user traffic counters enabled, so every user it creates is level 0 —
	// a user at another level would silently stop being billed.
	Level uint32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	// Email is the stats key, not an address. Xray reports traffic under
	// user>>>{email}>>>traffic>>>uplink, which is what the billing pipeline joins on.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Account is the protocol-specific credential, wrapped in a TypedMessage.
	Account       *serial.TypedMessage `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_xray_common_protocol_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_xray_common_protocol_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_xray_common_protocol_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAccount() *serial.TypedMessage {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_xray_common_protocol_user_proto protoreflect.FileDescriptor

const file_xray_common_protocol_user_proto_rawDesc = "" +
	"\n" +
	"\x1fxray/common/protocol/user.proto\x12\x14xray.common.protocol\x1a&xray/common/serial/typed_message.proto\"n\n" +
	"\x04User\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12:\n" +
	"\aaccount\x18\x03 \x01(\v2 .xray.common.serial.TypedMessageR\aaccountBCZAgithub.com/xraypanel/panel/internal/xray/common/protocol;protocolb\x06proto3"

var (
	file_xray_common_protocol_user_proto_rawDescOnce sync.Once
	file_xray_common_protocol_user_proto_rawDescData []byte
)

func file_xray_common_protocol_user_proto_rawDescGZIP() []byte {
	file_xray_common_protocol_user_proto_rawDescOnce.Do(func() {
		file_xray_common_protocol_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xray_common_protocol_user_proto_rawDesc), len(file_xray_common_protocol_user_proto_rawDesc)))
	})
	return file_xray_common_protocol_user_proto_rawDescData
}

var file_xray_common_protocol_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xray_common_protocol_user_proto_goTypes = []any{
	(*User)(nil),                // 0: xray.common.protocol.User
	(*serial.TypedMessage)(nil), // 1: xray.common.serial.TypedMessage
}
var file_xray_common_protocol_user_proto_depIdxs = []int32{
	1, // 0: xray.common.protocol.User.account:type_name -> xray.common.serial.TypedMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xray_common_protocol_user_proto_init() }
func file_xray_common_protocol_user_proto_init() {
	if File_xray_common_protocol_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xray_common_protocol_user_proto_rawDesc), len(file_xray_common_protocol_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xray_common_protocol_user_proto_goTypes,
		DependencyIndexes: file_xray_common_protocol_user_proto_depIdxs,
		MessageInfos:      file_xray_common_protocol_user_proto_msgTypes,
	}.Build()
	File_xray_common_protocol_user_proto = out.File
	file_xray_common_protocol_user_proto_goTypes = nil
	file_xray_common_protocol_user_proto_depIdxs = nil
}
