// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nodectl/v1/nodectl.proto

package nodectlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeControl_Enroll_FullMethodName  = "/nodectl.v1.NodeControl/Enroll"
	NodeControl_Control_FullMethodName = "/nodectl.v1.NodeControl/Control"
)

// NodeControlClient is the client API for NodeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeControl is the only interface between the control plane and a node.
//
// The node dials the panel, never the reverse: nodes sit behind NAT, have no
// inbound management port, and their liveness is simply whether their stream is
// open. That makes the panel the gRPC server, and a node's identity the client
// certificate it presents (see docs/node-protocol.md).
type NodeControlClient interface {
	// Enroll exchanges a single-use enrollment token for a client certificate.
	//
	// This is the one method that accepts a connection without a client
	// certificate, because it is how a node obtains one. Everything else
	// requires mutual TLS.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// Control is the long-lived bidirectional stream a node keeps open for as
	// long as it is running. The panel pushes desired state down it and the node
	// reports back; an open stream is what "connected" means.
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, PanelMessage], error)
}

type nodeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlClient(cc grpc.ClientConnInterface) NodeControlClient {
	return &nodeControlClient{cc}
}

func (c *nodeControlClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, NodeControl_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, PanelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeControl_ServiceDesc.Streams[0], NodeControl_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeMessage, PanelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_ControlClient = grpc.BidiStreamingClient[NodeMessage, PanelMessage]

// NodeControlServer is the server API for NodeControl service.
// All implementations must embed UnimplementedNodeControlServer
// for forward compatibility.
//
// NodeControl is the only interface between the control plane and a node.
//
// The node dials the panel, never the reverse: nodes sit behind NAT, have no
// inbound management port, and their liveness is simply whether their stream is
// open. That makes the panel the gRPC server, and a node's identity the client
// certificate it presents (see docs/node-protocol.md).
type NodeControlServer interface {
	// Enroll exchanges a single-use enrollment token for a client certificate.
	//
	// This is the one method that accepts a connection without a client
	// certificate, because it is how a node obtains one. Everything else
	// requires mutual TLS.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// Control is the long-lived bidirectional stream a node keeps open for as
	// long as it is running. The panel pushes desired state down it and the node
	// reports back; an open stream is what "connected" means.
	Control(grpc.BidiStreamingServer[NodeMessage, PanelMessage]) error
	mustEmbedUnimplementedNodeControlServer()
}

// UnimplementedNodeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControlServer struct{}

func (UnimplementedNodeControlServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedNodeControlServer) Control(grpc.BidiStreamingServer[NodeMessage, PanelMessage]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedNodeControlServer) mustEmbedUnimplementedNodeControlServer() {}
func (UnimplementedNodeControlServer) testEmbeddedByValue()                     {}

// UnsafeNodeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServer will
// result in compilation errors.
type UnsafeNodeControlServer interface {
	mustEmbedUnimplementedNodeControlServer()
}

func RegisterNodeControlServer(s grpc.ServiceRegistrar, srv NodeControlServer) {
	// If the following call panics, it indicates UnimplementedNodeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeControl_ServiceDesc, srv)
}

func _NodeControl_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeControlServer).Control(&grpc.GenericServerStream[NodeMessage, PanelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_ControlServer = grpc.BidiStreamingServer[NodeMessage, PanelMessage]

// NodeControl_ServiceDesc is the grpc.ServiceDesc for NodeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodectl.v1.NodeControl",
	HandlerType: (*NodeControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _NodeControl_Enroll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _NodeControl_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nodectl/v1/nodectl.proto",
}
