// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nodectl/v1/nodectl.proto

package nodectlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token is the single-use secret an administrator issued for one node.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// CsrPem is a PKCS#10 certificate request in PEM form.
	//
	// The node generates its own key pair and sends only the request, so the
	// private key never crosses the wire and the panel never holds it. The panel
	// takes the public key and ignores the requested subject: naming is the
	// panel's business, not the applicant's.
	CsrPem string `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// Advisory, recorded for the operator's benefit. Never trusted for any
	// decision: it is whatever the caller chose to send.
	AgentVersion  string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CertificatePem is the issued client certificate.
	CertificatePem string `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	// CaPem is the certificate authority the node must verify the panel against
	// on every later connection.
	CaPem string `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	// The identity the panel assigned. The node stores it for its own logs; the
	// panel re-derives it from the certificate on every connection rather than
	// believing what the node claims.
	NodeId   int64  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName string `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// ServerName is the name the node must require in the panel's certificate.
	// It is a fixed internal name rather than the address being dialled, so that
	// moving the panel does not require reissuing certificates.
	ServerName string `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// NotAfter is when this certificate stops being accepted, as RFC 3339. The
	// node logs it so an expiry is visible before it causes an outage.
	NotAfter      string `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *EnrollResponse) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

func (x *EnrollResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *EnrollResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EnrollResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *EnrollResponse) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_Hello
	//	*NodeMessage_Heartbeat
	//	*NodeMessage_ApplyResult
	//	*NodeMessage_TrafficBatch
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NodeMessage) GetApplyResult() *ApplyResult {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_ApplyResult); ok {
			return x.ApplyResult
		}
	}
	return nil
}

func (x *NodeMessage) GetTrafficBatch() *TrafficBatch {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_TrafficBatch); ok {
			return x.TrafficBatch
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type NodeMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type NodeMessage_ApplyResult struct {
	ApplyResult *ApplyResult `protobuf:"bytes,3,opt,name=apply_result,json=applyResult,proto3,oneof"`
}

type NodeMessage_TrafficBatch struct {
	// Reserved for M9: batched traffic deltas. Declared here so that adding
	// it later is not a change to the shape of this message.
	TrafficBatch *TrafficBatch `protobuf:"bytes,4,opt,name=traffic_batch,json=trafficBatch,proto3,oneof"`
}

func (*NodeMessage_Hello) isNodeMessage_Payload() {}

func (*NodeMessage_Heartbeat) isNodeMessage_Payload() {}

func (*NodeMessage_ApplyResult) isNodeMessage_Payload() {}

func (*NodeMessage_TrafficBatch) isNodeMessage_Payload() {}

// Hello is the first message on every stream. The panel answers with HelloAck.
type Hello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// XrayVersion is what the child process reports, or empty when it has not
	// started yet.
	XrayVersion string `protobuf:"bytes,2,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	// AppliedVersion is the config version the node currently has running, or 0
	// when it has none. The panel uses it to decide whether the node is behind.
	AppliedVersion int64 `protobuf:"varint,3,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	// StartedAt is when the agent process started, as RFC 3339.
	StartedAt     string `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

func (x *Hello) GetAppliedVersion() int64 {
	if x != nil {
		return x.AppliedVersion
	}
	return 0
}

func (x *Hello) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SentAt is the node's clock, as RFC 3339. It is recorded but not trusted:
	// the panel stamps its own arrival time, so a node with a wrong clock cannot
	// make itself look alive.
	SentAt string `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// XrayRunning is false when the supervisor has no healthy child process,
	// which is a node that is connected and not serving traffic.
	XrayRunning    bool  `protobuf:"varint,2,opt,name=xray_running,json=xrayRunning,proto3" json:"xray_running,omitempty"`
	AppliedVersion int64 `protobuf:"varint,3,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	// ActiveUsers is how many users the node currently has loaded into Xray.
	ActiveUsers   int64 `protobuf:"varint,4,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *Heartbeat) GetXrayRunning() bool {
	if x != nil {
		return x.XrayRunning
	}
	return false
}

func (x *Heartbeat) GetAppliedVersion() int64 {
	if x != nil {
		return x.AppliedVersion
	}
	return 0
}

func (x *Heartbeat) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

// ApplyResult reports the outcome of an ApplyConfig. Implemented in M7.
type ApplyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// Error is empty when ok is true.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Restarted records whether the core had to be restarted, which is the
	// signal that a change was structural rather than a runtime user edit.
	Restarted     bool `protobuf:"varint,4,opt,name=restarted,proto3" json:"restarted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResult) Reset() {
	*x = ApplyResult{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResult) ProtoMessage() {}

func (x *ApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResult.ProtoReflect.Descriptor instead.
func (*ApplyResult) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyResult) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ApplyResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ApplyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyResult) GetRestarted() bool {
	if x != nil {
		return x.Restarted
	}
	return false
}

// TrafficBatch carries traffic deltas. The batch id is what makes a retry after a
// reconnect safe to apply twice: the panel records it and ignores a batch it has
// already stored.
type TrafficBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Deltas        []*TrafficDelta        `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficBatch) Reset() {
	*x = TrafficBatch{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficBatch) ProtoMessage() {}

func (x *TrafficBatch) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficBatch.ProtoReflect.Descriptor instead.
func (*TrafficBatch) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{6}
}

func (x *TrafficBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *TrafficBatch) GetDeltas() []*TrafficDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type TrafficDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// XrayEmail is the immutable stats key, not the username (ADR-007).
	XrayEmail string `protobuf:"bytes,1,opt,name=xray_email,json=xrayEmail,proto3" json:"xray_email,omitempty"`
	Uplink    int64  `protobuf:"varint,2,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink  int64  `protobuf:"varint,3,opt,name=downlink,proto3" json:"downlink,omitempty"`
	// Hour is the UTC hour the traffic is attributed to, as RFC 3339.
	Hour          string `protobuf:"bytes,4,opt,name=hour,proto3" json:"hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficDelta) Reset() {
	*x = TrafficDelta{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficDelta) ProtoMessage() {}

func (x *TrafficDelta) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficDelta.ProtoReflect.Descriptor instead.
func (*TrafficDelta) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{7}
}

func (x *TrafficDelta) GetXrayEmail() string {
	if x != nil {
		return x.XrayEmail
	}
	return ""
}

func (x *TrafficDelta) GetUplink() int64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *TrafficDelta) GetDownlink() int64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *TrafficDelta) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

type PanelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PanelMessage_HelloAck
	//	*PanelMessage_ApplyConfig
	//	*PanelMessage_TrafficAck
	Payload       isPanelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelMessage) Reset() {
	*x = PanelMessage{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelMessage) ProtoMessage() {}

func (x *PanelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelMessage.ProtoReflect.Descriptor instead.
func (*PanelMessage) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{8}
}

func (x *PanelMessage) GetPayload() isPanelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PanelMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *PanelMessage) GetApplyConfig() *ApplyConfig {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_ApplyConfig); ok {
			return x.ApplyConfig
		}
	}
	return nil
}

func (x *PanelMessage) GetTrafficAck() *TrafficAck {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_TrafficAck); ok {
			return x.TrafficAck
		}
	}
	return nil
}

type isPanelMessage_Payload interface {
	isPanelMessage_Payload()
}

type PanelMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type PanelMessage_ApplyConfig struct {
	// The desired configuration.
	ApplyConfig *ApplyConfig `protobuf:"bytes,2,opt,name=apply_config,json=applyConfig,proto3,oneof"`
}

type PanelMessage_TrafficAck struct {
	// Confirmation that a traffic batch has been stored.
	TrafficAck *TrafficAck `protobuf:"bytes,3,opt,name=traffic_ack,json=trafficAck,proto3,oneof"`
}

func (*PanelMessage_HelloAck) isPanelMessage_Payload() {}

func (*PanelMessage_ApplyConfig) isPanelMessage_Payload() {}

func (*PanelMessage_TrafficAck) isPanelMessage_Payload() {}

// TrafficAck tells a node it may forget a batch.
//
// Without it a node could only guess: dropping a batch when the send succeeded would
// lose traffic whenever the panel failed to store it, and keeping every batch for ever
// would fill the node's volume. The node keeps a batch until this arrives and resends it
// on the next connection, which is safe because the panel deduplicates by batch id.
type TrafficAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BatchId string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// Stored is false when the panel could not store the batch; the node keeps it and
	// tries again. An already-known batch is reported as stored, because from the
	// node's point of view it is.
	Stored bool `protobuf:"varint,2,opt,name=stored,proto3" json:"stored,omitempty"`
	// Error is for the node's log when stored is false.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficAck) Reset() {
	*x = TrafficAck{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficAck) ProtoMessage() {}

func (x *TrafficAck) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficAck.ProtoReflect.Descriptor instead.
func (*TrafficAck) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{9}
}

func (x *TrafficAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *TrafficAck) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *TrafficAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HelloAck struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeId   int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// DesiredVersion is the config version the panel wants running. When it
	// differs from what the node reported, an ApplyConfig follows.
	DesiredVersion int64 `protobuf:"varint,3,opt,name=desired_version,json=desiredVersion,proto3" json:"desired_version,omitempty"`
	// HeartbeatSeconds is how often the node should send a Heartbeat. The panel
	// owns this interval so it can be tuned without redeploying nodes.
	HeartbeatSeconds int32 `protobuf:"varint,4,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"`
	// PanelTime is the panel's clock as RFC 3339, so a node with a skewed clock
	// can say so in its logs.
	PanelTime     string `protobuf:"bytes,5,opt,name=panel_time,json=panelTime,proto3" json:"panel_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{10}
}

func (x *HelloAck) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HelloAck) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HelloAck) GetDesiredVersion() int64 {
	if x != nil {
		return x.DesiredVersion
	}
	return 0
}

func (x *HelloAck) GetHeartbeatSeconds() int32 {
	if x != nil {
		return x.HeartbeatSeconds
	}
	return 0
}

func (x *HelloAck) GetPanelTime() string {
	if x != nil {
		return x.PanelTime
	}
	return ""
}

// ApplyConfig is the whole desired state of a node. Implemented in M7.
type ApplyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// ConfigJson is the complete Xray configuration, already patched. Nodes hold
	// no configuration of their own (ADR-003).
	ConfigJson []byte `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// StructuralHash covers everything except the user lists, so the node can
	// tell a change that needs a core restart from one that does not (ADR-009).
	StructuralHash string `protobuf:"bytes,3,opt,name=structural_hash,json=structuralHash,proto3" json:"structural_hash,omitempty"`
	// InboundHashes is keyed by inbound tag, for the same decision per inbound.
	InboundHashes map[string]string `protobuf:"bytes,4,rep,name=inbound_hashes,json=inboundHashes,proto3" json:"inbound_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfig) Reset() {
	*x = ApplyConfig{}
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfig) ProtoMessage() {}

func (x *ApplyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_nodectl_v1_nodectl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfig.ProtoReflect.Descriptor instead.
func (*ApplyConfig) Descriptor() ([]byte, []int) {
	return file_nodectl_v1_nodectl_proto_rawDescGZIP(), []int{11}
}

func (x *ApplyConfig) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ApplyConfig) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ApplyConfig) GetStructuralHash() string {
	if x != nil {
		return x.StructuralHash
	}
	return ""
}

func (x *ApplyConfig) GetInboundHashes() map[string]string {
	if x != nil {
		return x.InboundHashes
	}
	return nil
}

var File_nodectl_v1_nodectl_proto protoreflect.FileDescriptor

const file_nodectl_v1_nodectl_proto_rawDesc = "" +
	"\n" +
	"\x18nodectl/v1/nodectl.proto\x12\n" +
	"nodectl.v1\"\x7f\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\tR\x06csrPem\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\xc4\x01\n" +
	"\x0eEnrollResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\tR\x0ecertificatePem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\tR\x05caPem\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x12\x1b\n" +
	"\tnot_after\x18\x06 \x01(\tR\bnotAfter\"\xf9\x01\n" +
	"\vNodeMessage\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.nodectl.v1.HelloH\x00R\x05hello\x125\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.nodectl.v1.HeartbeatH\x00R\theartbeat\x12<\n" +
	"\fapply_result\x18\x03 \x01(\v2\x17.nodectl.v1.ApplyResultH\x00R\vapplyResult\x12?\n" +
	"\rtraffic_batch\x18\x04 \x01(\v2\x18.nodectl.v1.TrafficBatchH\x00R\ftrafficBatchB\t\n" +
	"\apayload\"\x97\x01\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12!\n" +
	"\fxray_version\x18\x02 \x01(\tR\vxrayVersion\x12'\n" +
	"\x0fapplied_version\x18\x03 \x01(\x03R\x0eappliedVersion\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\"\x93\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\asent_at\x18\x01 \x01(\tR\x06sentAt\x12!\n" +
	"\fxray_running\x18\x02 \x01(\bR\vxrayRunning\x12'\n" +
	"\x0fapplied_version\x18\x03 \x01(\x03R\x0eappliedVersion\x12!\n" +
	"\factive_users\x18\x04 \x01(\x03R\vactiveUsers\"x\n" +
	"\vApplyResult\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1c\n" +
	"\trestarted\x18\x04 \x01(\bR\trestarted\"[\n" +
	"\fTrafficBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x120\n" +
	"\x06deltas\x18\x02 \x03(\v2\x18.nodectl.v1.TrafficDeltaR\x06deltas\"u\n" +
	"\fTrafficDelta\x12\x1d\n" +
	"\n" +
	"xray_email\x18\x01 \x01(\tR\txrayEmail\x12\x16\n" +
	"\x06uplink\x18\x02 \x01(\x03R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x03 \x01(\x03R\bdownlink\x12\x12\n" +
	"\x04hour\x18\x04 \x01(\tR\x04hour\"\xc7\x01\n" +
	"\fPanelMessage\x123\n" +
	"\thello_ack\x18\x01 \x01(\v2\x14.nodectl.v1.HelloAckH\x00R\bhelloAck\x12<\n" +
	"\fapply_config\x18\x02 \x01(\v2\x17.nodectl.v1.ApplyConfigH\x00R\vapplyConfig\x129\n" +
	"\vtraffic_ack\x18\x03 \x01(\v2\x16.nodectl.v1.TrafficAckH\x00R\n" +
	"trafficAckB\t\n" +
	"\apayload\"U\n" +
	"\n" +
	"TrafficAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x16\n" +
	"\x06stored\x18\x02 \x01(\bR\x06stored\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xb5\x01\n" +
	"\bHelloAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12'\n" +
	"\x0fdesired_version\x18\x03 \x01(\x03R\x0edesiredVersion\x12+\n" +
	"\x11heartbeat_seconds\x18\x04 \x01(\x05R\x10heartbeatSeconds\x12\x1d\n" +
	"\n" +
	"panel_time\x18\x05 \x01(\tR\tpanelTime\"\x93\x02\n" +
	"\vApplyConfig\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\x12'\n" +
	"\x0fstructural_hash\x18\x03 \x01(\tR\x0estructuralHash\x12Q\n" +
	"\x0einbound_hashes\x18\x04 \x03(\v2*.nodectl.v1.ApplyConfig.InboundHashesEntryR\rinboundHashes\x1a@\n" +
	"\x12InboundHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x90\x01\n" +
	"\vNodeControl\x12?\n" +
	"\x06Enroll\x12\x19.nodectl.v1.EnrollRequest\x1a\x1a.nodectl.v1.EnrollResponse\x12@\n" +
	"\aControl\x12\x17.nodectl.v1.NodeMessage\x1a\x18.nodectl.v1.PanelMessage(\x010\x01B:Z8github.com/xraypanel/panel/internal/nodectl/v1;nodectlv1b\x06proto3"

var (
	file_nodectl_v1_nodectl_proto_rawDescOnce sync.Once
	file_nodectl_v1_nodectl_proto_rawDescData []byte
)

func file_nodectl_v1_nodectl_proto_rawDescGZIP() []byte {
	file_nodectl_v1_nodectl_proto_rawDescOnce.Do(func() {
		file_nodectl_v1_nodectl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodectl_v1_nodectl_proto_rawDesc), len(file_nodectl_v1_nodectl_proto_rawDesc)))
	})
	return file_nodectl_v1_nodectl_proto_rawDescData
}

var file_nodectl_v1_nodectl_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_nodectl_v1_nodectl_proto_goTypes = []any{
	(*EnrollRequest)(nil),  // 0: nodectl.v1.EnrollRequest
	(*EnrollResponse)(nil), // 1: nodectl.v1.EnrollResponse
	(*NodeMessage)(nil),    // 2: nodectl.v1.NodeMessage
	(*Hello)(nil),          // 3: nodectl.v1.Hello
	(*Heartbeat)(nil),      // 4: nodectl.v1.Heartbeat
	(*ApplyResult)(nil),    // 5: nodectl.v1.ApplyResult
	(*TrafficBatch)(nil),   // 6: nodectl.v1.TrafficBatch
	(*TrafficDelta)(nil),   // 7: nodectl.v1.TrafficDelta
	(*PanelMessage)(nil),   // 8: nodectl.v1.PanelMessage
	(*TrafficAck)(nil),     // 9: nodectl.v1.TrafficAck
	(*HelloAck)(nil),       // 10: nodectl.v1.HelloAck
	(*ApplyConfig)(nil),    // 11: nodectl.v1.ApplyConfig
	nil,                    // 12: nodectl.v1.ApplyConfig.InboundHashesEntry
}
var file_nodectl_v1_nodectl_proto_depIdxs = []int32{
	3,  // 0: nodectl.v1.NodeMessage.hello:type_name -> nodectl.v1.Hello
	4,  // 1: nodectl.v1.NodeMessage.heartbeat:type_name -> nodectl.v1.Heartbeat
	5,  // 2: nodectl.v1.NodeMessage.apply_result:type_name -> nodectl.v1.ApplyResult
	6,  // 3: nodectl.v1.NodeMessage.traffic_batch:type_name -> nodectl.v1.TrafficBatch
	7,  // 4: nodectl.v1.TrafficBatch.deltas:type_name -> nodectl.v1.TrafficDelta
	10, // 5: nodectl.v1.PanelMessage.hello_ack:type_name -> nodectl.v1.HelloAck
	11, // 6: nodectl.v1.PanelMessage.apply_config:type_name -> nodectl.v1.ApplyConfig
	9,  // 7: nodectl.v1.PanelMessage.traffic_ack:type_name -> nodectl.v1.TrafficAck
	12, // 8: nodectl.v1.ApplyConfig.inbound_hashes:type_name -> nodectl.v1.ApplyConfig.InboundHashesEntry
	0,  // 9: nodectl.v1.NodeControl.Enroll:input_type -> nodectl.v1.EnrollRequest
	2,  // 10: nodectl.v1.NodeControl.Control:input_type -> nodectl.v1.NodeMessage
	1,  // 11: nodectl.v1.NodeControl.Enroll:output_type -> nodectl.v1.EnrollResponse
	8,  // 12: nodectl.v1.NodeControl.Control:output_type -> nodectl.v1.PanelMessage
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nodectl_v1_nodectl_proto_init() }
func file_nodectl_v1_nodectl_proto_init() {
	if File_nodectl_v1_nodectl_proto != nil {
		return
	}
	file_nodectl_v1_nodectl_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeMessage_Hello)(nil),
		(*NodeMessage_Heartbeat)(nil),
		(*NodeMessage_ApplyResult)(nil),
		(*NodeMessage_TrafficBatch)(nil),
	}
	file_nodectl_v1_nodectl_proto_msgTypes[8].OneofWrappers = []any{
		(*PanelMessage_HelloAck)(nil),
		(*PanelMessage_ApplyConfig)(nil),
		(*PanelMessage_TrafficAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodectl_v1_nodectl_proto_rawDesc), len(file_nodectl_v1_nodectl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodectl_v1_nodectl_proto_goTypes,
		DependencyIndexes: file_nodectl_v1_nodectl_proto_depIdxs,
		MessageInfos:      file_nodectl_v1_nodectl_proto_msgTypes,
	}.Build()
	File_nodectl_v1_nodectl_proto = out.File
	file_nodectl_v1_nodectl_proto_goTypes = nil
	file_nodectl_v1_nodectl_proto_depIdxs = nil
}
