// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: xray/proxy/trojan/account.proto

package trojan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account is a Trojan credential.
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_xray_proxy_trojan_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_xray_proxy_trojan_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_xray_proxy_trojan_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_xray_proxy_trojan_account_proto protoreflect.FileDescriptor

const file_xray_proxy_trojan_account_proto_rawDesc = "" +
	"\n" +
	"\x1fxray/proxy/trojan/account.proto\x12\x11xray.proxy.trojan\"%\n" +
	"\aAccount\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpasswordB>Z<github.com/xraypanel/panel/internal/xray/proxy/trojan;trojanb\x06proto3"

var (
	file_xray_proxy_trojan_account_proto_rawDescOnce sync.Once
	file_xray_proxy_trojan_account_proto_rawDescData []byte
)

func file_xray_proxy_trojan_account_proto_rawDescGZIP() []byte {
	file_xray_proxy_trojan_account_proto_rawDescOnce.Do(func() {
		file_xray_proxy_trojan_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xray_proxy_trojan_account_proto_rawDesc), len(file_xray_proxy_trojan_account_proto_rawDesc)))
	})
	return file_xray_proxy_trojan_account_proto_rawDescData
}

var file_xray_proxy_trojan_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xray_proxy_trojan_account_proto_goTypes = []any{
	(*Account)(nil), // 0: xray.proxy.trojan.Account
}
var file_xray_proxy_trojan_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xray_proxy_trojan_account_proto_init() }
func file_xray_proxy_trojan_account_proto_init() {
	if File_xray_proxy_trojan_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xray_proxy_trojan_account_proto_rawDesc), len(file_xray_proxy_trojan_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xray_proxy_trojan_account_proto_goTypes,
		DependencyIndexes: file_xray_proxy_trojan_account_proto_depIdxs,
		MessageInfos:      file_xray_proxy_trojan_account_proto_msgTypes,
	}.Build()
	File_xray_proxy_trojan_account_proto = out.File
	file_xray_proxy_trojan_account_proto_goTypes = nil
	file_xray_proxy_trojan_account_proto_depIdxs = nil
}
