// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: xray/common/serial/typed_message.proto

// This directory mirrors part of Xray-core's own wire contract, transcribed field
// number for field number from the schema of the version the node image pins. It is
// not a copy of the core's code and it is not a dependency on it: the core is
// importable only as a Go module that brings in gvisor, wireguard, quic-go and utls,
// which is a large surface to add to a control panel that proxies no traffic itself.
// See ADR-065.
//
// The proto package names must match the core's exactly, because they decide the gRPC
// method paths and the type strings inside TypedMessage. The directory layout matches
// them in turn so that the origin of each message is obvious.

package serial

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypedMessage is Xray's own equivalent of google.protobuf.Any, and the reason this
// file exists: the API takes operations and accounts wrapped in it.
type TypedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type is the fully qualified protobuf message name, with no type.googleapis.com
	// prefix. Getting this string wrong is the one mistake the wire format cannot
	// catch for us, so every value the agent sends is built from a constant and
	// exercised against a real core in the integration tests.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Value is the serialised message.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedMessage) Reset() {
	*x = TypedMessage{}
	mi := &file_xray_common_serial_typed_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedMessage) ProtoMessage() {}

func (x *TypedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_xray_common_serial_typed_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedMessage.ProtoReflect.Descriptor instead.
func (*TypedMessage) Descriptor() ([]byte, []int) {
	return file_xray_common_serial_typed_message_proto_rawDescGZIP(), []int{0}
}

func (x *TypedMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypedMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_xray_common_serial_typed_message_proto protoreflect.FileDescriptor

const file_xray_common_serial_typed_message_proto_rawDesc = "" +
	"\n" +
	"&xray/common/serial/typed_message.proto\x12\x12xray.common.serial\"8\n" +
	"\fTypedMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05valueB?Z=github.com/xraypanel/panel/internal/xray/common/serial;serialb\x06proto3"

var (
	file_xray_common_serial_typed_message_proto_rawDescOnce sync.Once
	file_xray_common_serial_typed_message_proto_rawDescData []byte
)

func file_xray_common_serial_typed_message_proto_rawDescGZIP() []byte {
	file_xray_common_serial_typed_message_proto_rawDescOnce.Do(func() {
		file_xray_common_serial_typed_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xray_common_serial_typed_message_proto_rawDesc), len(file_xray_common_serial_typed_message_proto_rawDesc)))
	})
	return file_xray_common_serial_typed_message_proto_rawDescData
}

var file_xray_common_serial_typed_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xray_common_serial_typed_message_proto_goTypes = []any{
	(*TypedMessage)(nil), // 0: xray.common.serial.TypedMessage
}
var file_xray_common_serial_typed_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xray_common_serial_typed_message_proto_init() }
func file_xray_common_serial_typed_message_proto_init() {
	if File_xray_common_serial_typed_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xray_common_serial_typed_message_proto_rawDesc), len(file_xray_common_serial_typed_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xray_common_serial_typed_message_proto_goTypes,
		DependencyIndexes: file_xray_common_serial_typed_message_proto_depIdxs,
		MessageInfos:      file_xray_common_serial_typed_message_proto_msgTypes,
	}.Build()
	File_xray_common_serial_typed_message_proto = out.File
	file_xray_common_serial_typed_message_proto_goTypes = nil
	file_xray_common_serial_typed_message_proto_depIdxs = nil
}
