// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: xray/app/proxyman/command/command.proto

package command

import (
	protocol "github.com/xraypanel/panel/internal/xray/common/protocol"
	serial "github.com/xraypanel/panel/internal/xray/common/serial"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddUserOperation adds one user to a running inbound.
type AddUserOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *protocol.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserOperation) Reset() {
	*x = AddUserOperation{}
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserOperation) ProtoMessage() {}

func (x *AddUserOperation) ProtoReflect() protoreflect.Message {
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserOperation.ProtoReflect.Descriptor instead.
func (*AddUserOperation) Descriptor() ([]byte, []int) {
	return file_xray_app_proxyman_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserOperation) GetUser() *protocol.User {
	if x != nil {
		return x.User
	}
	return nil
}

// RemoveUserOperation removes a user by stats key.
type RemoveUserOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserOperation) Reset() {
	*x = RemoveUserOperation{}
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserOperation) ProtoMessage() {}

func (x *RemoveUserOperation) ProtoReflect() protoreflect.Message {
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserOperation.ProtoReflect.Descriptor instead.
func (*RemoveUserOperation) Descriptor() ([]byte, []int) {
	return file_xray_app_proxyman_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveUserOperation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AlterInboundRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tag names the inbound, and matches the tag the panel generated.
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Operation is an AddUserOperation or a RemoveUserOperation.
	Operation     *serial.TypedMessage `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterInboundRequest) Reset() {
	*x = AlterInboundRequest{}
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterInboundRequest) ProtoMessage() {}

func (x *AlterInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterInboundRequest.ProtoReflect.Descriptor instead.
func (*AlterInboundRequest) Descriptor() ([]byte, []int) {
	return file_xray_app_proxyman_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *AlterInboundRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AlterInboundRequest) GetOperation() *serial.TypedMessage {
	if x != nil {
		return x.Operation
	}
	return nil
}

type AlterInboundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterInboundResponse) Reset() {
	*x = AlterInboundResponse{}
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterInboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterInboundResponse) ProtoMessage() {}

func (x *AlterInboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterInboundResponse.ProtoReflect.Descriptor instead.
func (*AlterInboundResponse) Descriptor() ([]byte, []int) {
	return file_xray_app_proxyman_command_command_proto_rawDescGZIP(), []int{3}
}

type RemoveInboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInboundRequest) Reset() {
	*x = RemoveInboundRequest{}
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInboundRequest) ProtoMessage() {}

func (x *RemoveInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInboundRequest.ProtoReflect.Descriptor instead.
func (*RemoveInboundRequest) Descriptor() ([]byte, []int) {
	return file_xray_app_proxyman_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveInboundRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type RemoveInboundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInboundResponse) Reset() {
	*x = RemoveInboundResponse{}
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInboundResponse) ProtoMessage() {}

func (x *RemoveInboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInboundResponse.ProtoReflect.Descriptor instead.
func (*RemoveInboundResponse) Descriptor() ([]byte, []int) {
	return file_xray_app_proxyman_command_command_proto_rawDescGZIP(), []int{5}
}

type GetInboundUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tag   string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Email empty means every user on the inbound.
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundUserRequest) Reset() {
	*x = GetInboundUserRequest{}
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUserRequest) ProtoMessage() {}

func (x *GetInboundUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUserRequest.ProtoReflect.Descriptor instead.
func (*GetInboundUserRequest) Descriptor() ([]byte, []int) {
	return file_xray_app_proxyman_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *GetInboundUserRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetInboundUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetInboundUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundUserResponse) Reset() {
	*x = GetInboundUserResponse{}
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUserResponse) ProtoMessage() {}

func (x *GetInboundUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xray_app_proxyman_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUserResponse.ProtoReflect.Descriptor instead.
func (*GetInboundUserResponse) Descriptor() ([]byte, []int) {
	return file_xray_app_proxyman_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *GetInboundUserResponse) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_xray_app_proxyman_command_command_proto protoreflect.FileDescriptor

const file_xray_app_proxyman_command_command_proto_rawDesc = "" +
	"\n" +
	"'xray/app/proxyman/command/command.proto\x12\x19xray.app.proxyman.command\x1a\x1fxray/common/protocol/user.proto\x1a&xray/common/serial/typed_message.proto\"B\n" +
	"\x10AddUserOperation\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.xray.common.protocol.UserR\x04user\"+\n" +
	"\x13RemoveUserOperation\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"g\n" +
	"\x13AlterInboundRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12>\n" +
	"\toperation\x18\x02 \x01(\v2 .xray.common.serial.TypedMessageR\toperation\"\x16\n" +
	"\x14AlterInboundResponse\"(\n" +
	"\x14RemoveInboundRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"\x17\n" +
	"\x15RemoveInboundResponse\"?\n" +
	"\x15GetInboundUserRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"J\n" +
	"\x16GetInboundUserResponse\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users2\xed\x02\n" +
	"\x0eHandlerService\x12o\n" +
	"\fAlterInbound\x12..xray.app.proxyman.command.AlterInboundRequest\x1a/.xray.app.proxyman.command.AlterInboundResponse\x12r\n" +
	"\rRemoveInbound\x12/.xray.app.proxyman.command.RemoveInboundRequest\x1a0.xray.app.proxyman.command.RemoveInboundResponse\x12v\n" +
	"\x0fGetInboundUsers\x120.xray.app.proxyman.command.GetInboundUserRequest\x1a1.xray.app.proxyman.command.GetInboundUserResponseBGZEgithub.com/xraypanel/panel/internal/xray/app/proxyman/command;commandb\x06proto3"

var (
	file_xray_app_proxyman_command_command_proto_rawDescOnce sync.Once
	file_xray_app_proxyman_command_command_proto_rawDescData []byte
)

func file_xray_app_proxyman_command_command_proto_rawDescGZIP() []byte {
	file_xray_app_proxyman_command_command_proto_rawDescOnce.Do(func() {
		file_xray_app_proxyman_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xray_app_proxyman_command_command_proto_rawDesc), len(file_xray_app_proxyman_command_command_proto_rawDesc)))
	})
	return file_xray_app_proxyman_command_command_proto_rawDescData
}

var file_xray_app_proxyman_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_xray_app_proxyman_command_command_proto_goTypes = []any{
	(*AddUserOperation)(nil),       // 0: xray.app.proxyman.command.AddUserOperation
	(*RemoveUserOperation)(nil),    // 1: xray.app.proxyman.command.RemoveUserOperation
	(*AlterInboundRequest)(nil),    // 2: xray.app.proxyman.command.AlterInboundRequest
	(*AlterInboundResponse)(nil),   // 3: xray.app.proxyman.command.AlterInboundResponse
	(*RemoveInboundRequest)(nil),   // 4: xray.app.proxyman.command.RemoveInboundRequest
	(*RemoveInboundResponse)(nil),  // 5: xray.app.proxyman.command.RemoveInboundResponse
	(*GetInboundUserRequest)(nil),  // 6: xray.app.proxyman.command.GetInboundUserRequest
	(*GetInboundUserResponse)(nil), // 7: xray.app.proxyman.command.GetInboundUserResponse
	(*protocol.User)(nil),          // 8: xray.common.protocol.User
	(*serial.TypedMessage)(nil),    // 9: xray.common.serial.TypedMessage
}
var file_xray_app_proxyman_command_command_proto_depIdxs = []int32{
	8, // 0: xray.app.proxyman.command.AddUserOperation.user:type_name -> xray.common.protocol.User
	9, // 1: xray.app.proxyman.command.AlterInboundRequest.operation:type_name -> xray.common.serial.TypedMessage
	8, // 2: xray.app.proxyman.command.GetInboundUserResponse.users:type_name -> xray.common.protocol.User
	2, // 3: xray.app.proxyman.command.HandlerService.AlterInbound:input_type -> xray.app.proxyman.command.AlterInboundRequest
	4, // 4: xray.app.proxyman.command.HandlerService.RemoveInbound:input_type -> xray.app.proxyman.command.RemoveInboundRequest
	6, // 5: xray.app.proxyman.command.HandlerService.GetInboundUsers:input_type -> xray.app.proxyman.command.GetInboundUserRequest
	3, // 6: xray.app.proxyman.command.HandlerService.AlterInbound:output_type -> xray.app.proxyman.command.AlterInboundResponse
	5, // 7: xray.app.proxyman.command.HandlerService.RemoveInbound:output_type -> xray.app.proxyman.command.RemoveInboundResponse
	7, // 8: xray.app.proxyman.command.HandlerService.GetInboundUsers:output_type -> xray.app.proxyman.command.GetInboundUserResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_xray_app_proxyman_command_command_proto_init() }
func file_xray_app_proxyman_command_command_proto_init() {
	if File_xray_app_proxyman_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xray_app_proxyman_command_command_proto_rawDesc), len(file_xray_app_proxyman_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xray_app_proxyman_command_command_proto_goTypes,
		DependencyIndexes: file_xray_app_proxyman_command_command_proto_depIdxs,
		MessageInfos:      file_xray_app_proxyman_command_command_proto_msgTypes,
	}.Build()
	File_xray_app_proxyman_command_command_proto = out.File
	file_xray_app_proxyman_command_command_proto_goTypes = nil
	file_xray_app_proxyman_command_command_proto_depIdxs = nil
}
